const { all: sqliteAll } = require("../db/database");
const { getPgPool, getUserStoreState, listUsers } = require("./userStore");
const { SOLICITUD_ITEM_STATUS } = require("../config/solicitudItemFlow");

let initPromise = null;

function isOperationalPgEnabled() {
  return Boolean(getUserStoreState().persistent);
}

function getOperationalPool() {
  return getPgPool();
}

async function loadEquiposMap() {
  const rows = await sqliteAll("SELECT id, nombre_equipo FROM equipos ORDER BY id ASC");
  return new Map(rows.map((row) => [Number(row.id), row.nombre_equipo]));
}

async function loadUsersMap() {
  const rows = await listUsers({ estado: "todos" });
  return new Map(
    rows.map((row) => [
      Number(row.id),
      {
        id: Number(row.id),
        nombre: row.nombre,
        email: row.email,
        rol: row.rol,
        equipo_id: row.equipo_id === null || row.equipo_id === undefined ? null : Number(row.equipo_id),
      },
    ])
  );
}

async function ensureSchema() {
  const pg = getOperationalPool();
  if (!pg) {
    return;
  }

  await pg.query(`
    CREATE TABLE IF NOT EXISTS solicitudes (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      solicitante_id INTEGER NOT NULL,
      client_request_id TEXT,
      equipo TEXT,
      equipo_id INTEGER,
      repuesto TEXT NOT NULL,
      cantidad INTEGER NOT NULL,
      comentario TEXT,
      estado TEXT NOT NULL,
      reviewed_at TIMESTAMPTZ,
      reviewed_by INTEGER,
      dispatched_at TIMESTAMPTZ,
      dispatched_by INTEGER,
      received_at TIMESTAMPTZ,
      received_by INTEGER,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ
    )
  `);

  await pg.query(`
    CREATE TABLE IF NOT EXISTS solicitud_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      solicitud_id INTEGER NOT NULL,
      client_request_id TEXT,
      nombre_item TEXT NOT NULL,
      cantidad INTEGER NOT NULL,
      unidad_medida TEXT,
      codigo_referencia TEXT,
      usuario_final TEXT,
      comentario TEXT,
      estado_item TEXT NOT NULL DEFAULT '${SOLICITUD_ITEM_STATUS.POR_GESTIONAR}',
      comentario_gestion TEXT,
      encargado_id INTEGER,
      enviado_por_id INTEGER,
      recepcionado_por_id INTEGER,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ
    )
  `);

  await pg.query(`
    ALTER TABLE solicitudes
    ADD COLUMN IF NOT EXISTS client_request_id TEXT
  `);

  await pg.query(`
    ALTER TABLE solicitud_items
    ADD COLUMN IF NOT EXISTS client_request_id TEXT
  `);
  await pg.query(`
    ALTER TABLE solicitud_items
    ADD COLUMN IF NOT EXISTS unidad_medida TEXT
  `);
  await pg.query(`
    ALTER TABLE solicitud_items
    ADD COLUMN IF NOT EXISTS codigo_referencia TEXT
  `);
  await pg.query(`
    ALTER TABLE solicitud_items
    ADD COLUMN IF NOT EXISTS usuario_final TEXT
  `);
  await pg.query(`
    ALTER TABLE solicitud_items
    ADD COLUMN IF NOT EXISTS estado_item TEXT NOT NULL DEFAULT '${SOLICITUD_ITEM_STATUS.POR_GESTIONAR}'
  `);
  await pg.query(`
    ALTER TABLE solicitud_items
    ADD COLUMN IF NOT EXISTS comentario_gestion TEXT
  `);
  await pg.query(`
    ALTER TABLE solicitud_items
    ADD COLUMN IF NOT EXISTS encargado_id INTEGER
  `);
  await pg.query(`
    ALTER TABLE solicitud_items
    ADD COLUMN IF NOT EXISTS enviado_por_id INTEGER
  `);
  await pg.query(`
    ALTER TABLE solicitud_items
    ADD COLUMN IF NOT EXISTS recepcionado_por_id INTEGER
  `);
  await pg.query(`
    ALTER TABLE solicitud_items
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ
  `);
  await pg.query(
    `
      UPDATE solicitud_items
      SET estado_item = $1
      WHERE estado_item IS NULL OR BTRIM(estado_item) = ''
    `,
    [SOLICITUD_ITEM_STATUS.POR_GESTIONAR]
  );

  await pg.query(`
    CREATE TABLE IF NOT EXISTS solicitud_historial (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      solicitud_id INTEGER NOT NULL,
      accion TEXT NOT NULL,
      estado_anterior TEXT,
      estado_nuevo TEXT,
      detalle TEXT,
      actor_id INTEGER NOT NULL,
      actor_name TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await pg.query(`
    CREATE TABLE IF NOT EXISTS solicitud_mensajes (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      solicitud_id INTEGER NOT NULL,
      remitente_id INTEGER NOT NULL,
      destinatario_id INTEGER,
      mensaje TEXT,
      imagen_nombre TEXT,
      imagen_data TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await pg.query(`
    CREATE TABLE IF NOT EXISTS notificaciones (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tipo TEXT NOT NULL,
      titulo TEXT NOT NULL,
      mensaje TEXT NOT NULL,
      rol_destino TEXT,
      usuario_destino_id INTEGER,
      equipo_id INTEGER,
      referencia_id INTEGER,
      leida BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      read_at TIMESTAMPTZ
    )
  `);

  await pg.query("CREATE INDEX IF NOT EXISTS solicitudes_estado_idx ON solicitudes (estado, equipo_id, created_at DESC)");
  await pg.query("CREATE INDEX IF NOT EXISTS solicitudes_solicitante_idx ON solicitudes (solicitante_id, created_at DESC)");
  await pg.query("CREATE UNIQUE INDEX IF NOT EXISTS solicitudes_client_request_id_idx ON solicitudes (client_request_id) WHERE client_request_id IS NOT NULL");
  await pg.query("CREATE INDEX IF NOT EXISTS solicitud_items_solicitud_idx ON solicitud_items (solicitud_id, id ASC)");
  await pg.query("CREATE UNIQUE INDEX IF NOT EXISTS solicitud_items_client_request_id_idx ON solicitud_items (client_request_id) WHERE client_request_id IS NOT NULL");
  await pg.query("CREATE INDEX IF NOT EXISTS solicitud_historial_solicitud_idx ON solicitud_historial (solicitud_id, id ASC)");
  await pg.query("CREATE INDEX IF NOT EXISTS solicitud_mensajes_solicitud_idx ON solicitud_mensajes (solicitud_id, id ASC)");
  await pg.query("CREATE INDEX IF NOT EXISTS notificaciones_visibility_idx ON notificaciones (rol_destino, usuario_destino_id, equipo_id, created_at DESC)");

  await pg.query(`
    CREATE TABLE IF NOT EXISTS novedades (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tipo TEXT NOT NULL DEFAULT 'feature',
      titulo TEXT NOT NULL,
      descripcion TEXT,
      autor_nombre TEXT NOT NULL DEFAULT 'Admin',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
}

async function cleanupOrphanOperationalRows() {
  const pg = getOperationalPool();
  if (!pg) {
    return {
      solicitud_items: 0,
      solicitud_historial: 0,
      solicitud_mensajes: 0,
      notificaciones: 0,
    };
  }

  const counters = {
    solicitud_items: 0,
    solicitud_historial: 0,
    solicitud_mensajes: 0,
    notificaciones: 0,
  };

  const statements = [
    {
      key: "solicitud_items",
      sql: `
        DELETE FROM solicitud_items si
        WHERE NOT EXISTS (
          SELECT 1
          FROM solicitudes s
          WHERE s.id = si.solicitud_id
        )
      `,
    },
    {
      key: "solicitud_historial",
      sql: `
        DELETE FROM solicitud_historial sh
        WHERE NOT EXISTS (
          SELECT 1
          FROM solicitudes s
          WHERE s.id = sh.solicitud_id
        )
      `,
    },
    {
      key: "solicitud_mensajes",
      sql: `
        DELETE FROM solicitud_mensajes sm
        WHERE NOT EXISTS (
          SELECT 1
          FROM solicitudes s
          WHERE s.id = sm.solicitud_id
        )
      `,
    },
    {
      key: "notificaciones",
      sql: `
        DELETE FROM notificaciones n
        WHERE n.tipo LIKE 'SOLICITUD_%'
          AND n.referencia_id IS NOT NULL
          AND NOT EXISTS (
            SELECT 1
            FROM solicitudes s
            WHERE s.id = n.referencia_id
          )
      `,
    },
  ];

  for (const statement of statements) {
    const result = await pg.query(statement.sql);
    counters[statement.key] = Number(result.rowCount || 0);
  }

  return counters;
}

async function ensureReferentialConstraints() {
  const pg = getOperationalPool();
  if (!pg) {
    return;
  }

  const constraints = [
    {
      name: "solicitud_items_solicitud_fk",
      table: "solicitud_items",
      definition:
        "FOREIGN KEY (solicitud_id) REFERENCES solicitudes(id) ON DELETE CASCADE",
    },
    {
      name: "solicitud_historial_solicitud_fk",
      table: "solicitud_historial",
      definition:
        "FOREIGN KEY (solicitud_id) REFERENCES solicitudes(id) ON DELETE CASCADE",
    },
    {
      name: "solicitud_mensajes_solicitud_fk",
      table: "solicitud_mensajes",
      definition:
        "FOREIGN KEY (solicitud_id) REFERENCES solicitudes(id) ON DELETE CASCADE",
    },
  ];

  for (const constraint of constraints) {
    await pg.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint
          WHERE conname = '${constraint.name}'
        ) THEN
          ALTER TABLE ${constraint.table}
          ADD CONSTRAINT ${constraint.name}
          ${constraint.definition};
        END IF;
      END
      $$;
    `);
  }
}

async function syncSequence(client, tableName) {
  await client.query(
    `
      SELECT setval(
        pg_get_serial_sequence($1, 'id'),
        GREATEST(COALESCE((SELECT MAX(id) FROM ${tableName}), 1), 1),
        true
      )
    `,
    [tableName]
  );
}

async function bootstrapTableIfEmpty(client, tableName, sqliteQuery, mapRow) {
  const { rows: countRows } = await client.query(`SELECT COUNT(*)::int AS total FROM ${tableName}`);
  if (Number(countRows[0]?.total || 0) > 0) {
    return;
  }

  const sqliteRows = await sqliteAll(sqliteQuery);
  if (!sqliteRows.length) {
    return;
  }

  const { columns, values } = mapRow(sqliteRows[0]);
  const placeholders = columns.map((_, index) => `$${index + 1}`).join(", ");

  for (const row of sqliteRows) {
    const mapped = mapRow(row);
    await client.query(
      `INSERT INTO ${tableName} (${mapped.columns.join(", ")}) VALUES (${placeholders})`,
      mapped.values
    );
  }

  await syncSequence(client, tableName);
}

function normalizeSqliteBoolean(value) {
  return value === true || value === 1 || value === "1";
}

async function bootstrapFromSqlite() {
  const pg = getOperationalPool();
  if (!pg) {
    return;
  }

  const client = await pg.connect();
  try {
    await client.query("BEGIN");

    await bootstrapTableIfEmpty(
      client,
      "solicitudes",
      `
        SELECT
          id,
          solicitante_id,
          equipo,
          equipo_id,
          repuesto,
          cantidad,
          comentario,
          estado,
          reviewed_at,
          reviewed_by,
          dispatched_at,
          dispatched_by,
          received_at,
          received_by,
          created_at,
          updated_at
        FROM solicitudes
        ORDER BY id ASC
      `,
      (row) => ({
        columns: [
          "id",
          "solicitante_id",
          "equipo",
          "equipo_id",
          "repuesto",
          "cantidad",
          "comentario",
          "estado",
          "reviewed_at",
          "reviewed_by",
          "dispatched_at",
          "dispatched_by",
          "received_at",
          "received_by",
          "created_at",
          "updated_at",
        ],
        values: [
          Number(row.id),
          Number(row.solicitante_id),
          row.equipo || null,
          row.equipo_id === null || row.equipo_id === undefined ? null : Number(row.equipo_id),
          row.repuesto,
          Number(row.cantidad),
          row.comentario || null,
          row.estado,
          row.reviewed_at || null,
          row.reviewed_by === null || row.reviewed_by === undefined ? null : Number(row.reviewed_by),
          row.dispatched_at || null,
          row.dispatched_by === null || row.dispatched_by === undefined ? null : Number(row.dispatched_by),
          row.received_at || null,
          row.received_by === null || row.received_by === undefined ? null : Number(row.received_by),
          row.created_at || null,
          row.updated_at || null,
        ],
      })
    );

    await bootstrapTableIfEmpty(
      client,
      "solicitud_items",
      `
        SELECT
          id,
          solicitud_id,
          nombre_item,
          cantidad,
          unidad_medida,
          codigo_referencia,
          usuario_final,
          comentario,
          COALESCE(estado_item, '${SOLICITUD_ITEM_STATUS.POR_GESTIONAR}') AS estado_item,
          comentario_gestion,
          encargado_id,
          enviado_por_id,
          recepcionado_por_id,
          created_at,
          updated_at
        FROM solicitud_items
        ORDER BY id ASC
      `,
      (row) => ({
        columns: [
          "id",
          "solicitud_id",
          "nombre_item",
          "cantidad",
          "unidad_medida",
          "codigo_referencia",
          "usuario_final",
          "comentario",
          "estado_item",
          "comentario_gestion",
          "encargado_id",
          "enviado_por_id",
          "recepcionado_por_id",
          "created_at",
          "updated_at",
        ],
        values: [
          Number(row.id),
          Number(row.solicitud_id),
          row.nombre_item,
          Number(row.cantidad),
          row.unidad_medida || null,
          row.codigo_referencia || null,
          row.usuario_final || null,
          row.comentario || null,
          row.estado_item || SOLICITUD_ITEM_STATUS.POR_GESTIONAR,
          row.comentario_gestion || null,
          row.encargado_id === null || row.encargado_id === undefined ? null : Number(row.encargado_id),
          row.enviado_por_id === null || row.enviado_por_id === undefined ? null : Number(row.enviado_por_id),
          row.recepcionado_por_id === null || row.recepcionado_por_id === undefined ? null : Number(row.recepcionado_por_id),
          row.created_at || null,
          row.updated_at || null,
        ],
      })
    );

    await bootstrapTableIfEmpty(
      client,
      "solicitud_historial",
      `
        SELECT
          id,
          solicitud_id,
          accion,
          estado_anterior,
          estado_nuevo,
          detalle,
          actor_id,
          actor_name,
          created_at
        FROM solicitud_historial
        ORDER BY id ASC
      `,
      (row) => ({
        columns: [
          "id",
          "solicitud_id",
          "accion",
          "estado_anterior",
          "estado_nuevo",
          "detalle",
          "actor_id",
          "actor_name",
          "created_at",
        ],
        values: [
          Number(row.id),
          Number(row.solicitud_id),
          row.accion,
          row.estado_anterior || null,
          row.estado_nuevo || null,
          row.detalle || null,
          Number(row.actor_id),
          row.actor_name,
          row.created_at || null,
        ],
      })
    );

    await bootstrapTableIfEmpty(
      client,
      "solicitud_mensajes",
      `
        SELECT
          id,
          solicitud_id,
          remitente_id,
          destinatario_id,
          mensaje,
          imagen_nombre,
          imagen_data,
          created_at
        FROM solicitud_mensajes
        ORDER BY id ASC
      `,
      (row) => ({
        columns: [
          "id",
          "solicitud_id",
          "remitente_id",
          "destinatario_id",
          "mensaje",
          "imagen_nombre",
          "imagen_data",
          "created_at",
        ],
        values: [
          Number(row.id),
          Number(row.solicitud_id),
          Number(row.remitente_id),
          row.destinatario_id === null || row.destinatario_id === undefined ? null : Number(row.destinatario_id),
          row.mensaje || null,
          row.imagen_nombre || null,
          row.imagen_data || null,
          row.created_at || null,
        ],
      })
    );

    await bootstrapTableIfEmpty(
      client,
      "notificaciones",
      `
        SELECT
          id,
          tipo,
          titulo,
          mensaje,
          rol_destino,
          usuario_destino_id,
          equipo_id,
          referencia_id,
          leida,
          created_at,
          read_at
        FROM notificaciones
        ORDER BY id ASC
      `,
      (row) => ({
        columns: [
          "id",
          "tipo",
          "titulo",
          "mensaje",
          "rol_destino",
          "usuario_destino_id",
          "equipo_id",
          "referencia_id",
          "leida",
          "created_at",
          "read_at",
        ],
        values: [
          Number(row.id),
          row.tipo,
          row.titulo,
          row.mensaje,
          row.rol_destino || null,
          row.usuario_destino_id === null || row.usuario_destino_id === undefined ? null : Number(row.usuario_destino_id),
          row.equipo_id === null || row.equipo_id === undefined ? null : Number(row.equipo_id),
          row.referencia_id === null || row.referencia_id === undefined ? null : Number(row.referencia_id),
          normalizeSqliteBoolean(row.leida),
          row.created_at || null,
          row.read_at || null,
        ],
      })
    );

    await client.query("COMMIT");
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

async function initOperationalStore() {
  if (!isOperationalPgEnabled()) {
    return { provider: "sqlite", persistent: false };
  }

  if (!initPromise) {
    initPromise = (async () => {
      await ensureSchema();
      await bootstrapFromSqlite();
      const cleanupSummary = await cleanupOrphanOperationalRows();
      await ensureReferentialConstraints();
      if (Object.values(cleanupSummary).some((value) => Number(value) > 0)) {
        console.warn("[FMN] Se limpiaron registros huerfanos en PostgreSQL:", cleanupSummary);
      }
      return { provider: "postgres", persistent: true };
    })();
  }

  return initPromise;
}

module.exports = {
  initOperationalStore,
  isOperationalPgEnabled,
  getOperationalPool,
  loadEquiposMap,
  loadUsersMap,
  cleanupOrphanOperationalRows,
  ensureReferentialConstraints,
};
