const { Pool } = require("pg");
const { all: sqliteAll, get: sqliteGet, run: sqliteRun } = require("../db/database");
const { normalizeEmail, normalizeText } = require("../utils/validators");
const { normalizeRole } = require("../config/appRoles");
const { HttpError } = require("../utils/httpError");

const DATABASE_URL = String(process.env.DATABASE_URL || "").trim();
const PG_ENABLED = Boolean(DATABASE_URL);
const MIRROR_SYNC_TTL_MS = 5000;

let pool = null;
let initPromise = null;
let legacyPasswordColumnExists = null;
let lastMirrorSyncAt = 0;

function isLocalPostgresUrl(connectionString) {
  return /localhost|127\.0\.0\.1/i.test(connectionString);
}

function getPool() {
  if (!PG_ENABLED) {
    return null;
  }

  if (!pool) {
    pool = new Pool({
      connectionString: DATABASE_URL,
      ssl:
        process.env.PGSSLMODE === "disable" || isLocalPostgresUrl(DATABASE_URL)
          ? false
          : { rejectUnauthorized: false },
    });
  }

  return pool;
}

function toSqliteDateTime(value) {
  if (!value) {
    return null;
  }

  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) {
    return null;
  }

  const year = date.getUTCFullYear();
  const month = String(date.getUTCMonth() + 1).padStart(2, "0");
  const day = String(date.getUTCDate()).padStart(2, "0");
  const hour = String(date.getUTCHours()).padStart(2, "0");
  const minute = String(date.getUTCMinutes()).padStart(2, "0");
  const second = String(date.getUTCSeconds()).padStart(2, "0");
  return `${year}-${month}-${day} ${hour}:${minute}:${second}`;
}

async function hasLegacyPasswordColumn() {
  if (legacyPasswordColumnExists !== null) {
    return legacyPasswordColumnExists;
  }

  const columns = await sqliteAll("PRAGMA table_info(usuarios)");
  legacyPasswordColumnExists = columns.some((column) => column.name === "password");
  return legacyPasswordColumnExists;
}

async function loadEquiposMap() {
  const rows = await sqliteAll("SELECT id, nombre_equipo FROM equipos");
  return new Map(rows.map((row) => [Number(row.id), row.nombre_equipo]));
}

function normalizeBoolean(value) {
  return value === true || value === 1 || value === "1";
}

function mapBaseUser(row, equiposMap = new Map()) {
  if (!row) {
    return null;
  }

  const equipoId = row.equipo_id === null || row.equipo_id === undefined ? null : Number(row.equipo_id);
  const nombre = normalizeText(row.nombre || row.name);
  const email = normalizeEmail(row.email);
  const rol = normalizeRole(row.rol || row.role);
  const activo = normalizeBoolean(row.activo ?? row.active);
  const archivado = normalizeBoolean(row.archivado);
  const fechaCreacion = row.fecha_creacion || row.created_at;
  const fechaArchivado = row.fecha_archivado || null;

  return {
    id: Number(row.id),
    nombre,
    email,
    password_hash: row.password_hash || null,
    rol,
    equipo_id: equipoId,
    equipo_nombre: row.equipo_nombre || (equipoId ? equiposMap.get(equipoId) || null : null),
    activo,
    archivado,
    fecha_archivado: fechaArchivado,
    archivado_por: row.archivado_por === undefined || row.archivado_por === null ? null : Number(row.archivado_por),
    fecha_creacion: fechaCreacion,
    created_at: fechaCreacion,
  };
}

async function ensurePgSchema() {
  const pg = getPool();
  if (!pg) {
    return;
  }

  await pg.query(`
    CREATE TABLE IF NOT EXISTS usuarios_auth (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nombre TEXT NOT NULL,
      email TEXT NOT NULL,
      password_hash TEXT NOT NULL,
      rol TEXT NOT NULL,
      equipo_id INTEGER,
      activo BOOLEAN NOT NULL DEFAULT TRUE,
      archivado BOOLEAN NOT NULL DEFAULT FALSE,
      fecha_archivado TIMESTAMPTZ,
      archivado_por INTEGER,
      fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await pg.query(`
    CREATE UNIQUE INDEX IF NOT EXISTS usuarios_auth_email_unique_idx
    ON usuarios_auth ((LOWER(BTRIM(email))))
  `);

  await pg.query(`
    CREATE INDEX IF NOT EXISTS usuarios_auth_estado_idx
    ON usuarios_auth (archivado, activo, rol)
  `);
}

async function bootstrapPgUsersFromSqlite() {
  const pg = getPool();
  if (!pg) {
    return;
  }

  const { rows: countRows } = await pg.query("SELECT COUNT(*)::int AS total FROM usuarios_auth");
  if (Number(countRows[0]?.total || 0) > 0) {
    return;
  }

  const sqliteUsers = await sqliteAll(`
    SELECT
      id,
      nombre,
      email,
      password_hash,
      rol,
      equipo_id,
      activo,
      COALESCE(archivado, 0) AS archivado,
      fecha_archivado,
      archivado_por,
      fecha_creacion
    FROM usuarios
    ORDER BY id ASC
  `);

  if (!sqliteUsers.length) {
    return;
  }

  const client = await pg.connect();
  try {
    await client.query("BEGIN");
    for (const row of sqliteUsers) {
      await client.query(
        `
          INSERT INTO usuarios_auth (
            id,
            nombre,
            email,
            password_hash,
            rol,
            equipo_id,
            activo,
            archivado,
            fecha_archivado,
            archivado_por,
            fecha_creacion,
            updated_at
          )
          VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW())
          ON CONFLICT (id) DO NOTHING
        `,
        [
          Number(row.id),
          normalizeText(row.nombre),
          normalizeEmail(row.email),
          row.password_hash || "",
          normalizeRole(row.rol),
          row.equipo_id === null || row.equipo_id === undefined ? null : Number(row.equipo_id),
          Number(row.activo) === 1,
          Number(row.archivado) === 1,
          row.fecha_archivado || null,
          row.archivado_por === null || row.archivado_por === undefined ? null : Number(row.archivado_por),
          row.fecha_creacion || null,
        ]
      );
    }

    await client.query(`
      SELECT setval(
        pg_get_serial_sequence('usuarios_auth', 'id'),
        GREATEST(COALESCE((SELECT MAX(id) FROM usuarios_auth), 1), 1),
        true
      )
    `);
    await client.query("COMMIT");
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

async function fetchAllPgUsers() {
  const pg = getPool();
  if (!pg) {
    return [];
  }

  const { rows } = await pg.query(`
    SELECT
      id,
      nombre,
      email,
      password_hash,
      rol,
      equipo_id,
      activo,
      archivado,
      fecha_archivado,
      archivado_por,
      fecha_creacion
    FROM usuarios_auth
    ORDER BY id ASC
  `);

  const equiposMap = await loadEquiposMap();
  return rows.map((row) => mapBaseUser(row, equiposMap));
}

async function syncSingleUserToSqlite(user) {
  if (!user) {
    return;
  }

  const includeLegacyPassword = await hasLegacyPasswordColumn();
  const existing = await sqliteGet("SELECT id FROM usuarios WHERE id = ?", [user.id]);
  const params = [
    user.nombre,
    user.email,
    user.password_hash,
    user.rol,
    user.equipo_id,
    user.activo ? 1 : 0,
    user.archivado ? 1 : 0,
    user.fecha_archivado,
    user.archivado_por,
    toSqliteDateTime(user.fecha_creacion) || user.fecha_creacion,
    user.id,
  ];

  if (existing) {
    const updateSql = includeLegacyPassword
      ? `
          UPDATE usuarios
          SET
            nombre = ?,
            email = ?,
            password_hash = ?,
            password = ?,
            rol = ?,
            equipo_id = ?,
            activo = ?,
            archivado = ?,
            fecha_archivado = ?,
            archivado_por = ?,
            fecha_creacion = ?
          WHERE id = ?
        `
      : `
          UPDATE usuarios
          SET
            nombre = ?,
            email = ?,
            password_hash = ?,
            rol = ?,
            equipo_id = ?,
            activo = ?,
            archivado = ?,
            fecha_archivado = ?,
            archivado_por = ?,
            fecha_creacion = ?
          WHERE id = ?
        `;

    const updateParams = includeLegacyPassword
      ? [
          user.nombre,
          user.email,
          user.password_hash,
          user.password_hash,
          user.rol,
          user.equipo_id,
          user.activo ? 1 : 0,
          user.archivado ? 1 : 0,
          user.fecha_archivado,
          user.archivado_por,
          toSqliteDateTime(user.fecha_creacion) || user.fecha_creacion,
          user.id,
        ]
      : params;

    await sqliteRun(updateSql, updateParams);
    return;
  }

  const insertSql = includeLegacyPassword
    ? `
        INSERT INTO usuarios (
          id,
          nombre,
          email,
          password_hash,
          password,
          rol,
          equipo_id,
          activo,
          archivado,
          fecha_archivado,
          archivado_por,
          fecha_creacion
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `
    : `
        INSERT INTO usuarios (
          id,
          nombre,
          email,
          password_hash,
          rol,
          equipo_id,
          activo,
          archivado,
          fecha_archivado,
          archivado_por,
          fecha_creacion
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `;

  const insertParams = includeLegacyPassword
    ? [
        user.id,
        user.nombre,
        user.email,
        user.password_hash,
        user.password_hash,
        user.rol,
        user.equipo_id,
        user.activo ? 1 : 0,
        user.archivado ? 1 : 0,
        user.fecha_archivado,
        user.archivado_por,
        toSqliteDateTime(user.fecha_creacion) || user.fecha_creacion,
      ]
    : [
        user.id,
        user.nombre,
        user.email,
        user.password_hash,
        user.rol,
        user.equipo_id,
        user.activo ? 1 : 0,
        user.archivado ? 1 : 0,
        user.fecha_archivado,
        user.archivado_por,
        toSqliteDateTime(user.fecha_creacion) || user.fecha_creacion,
      ];

  await sqliteRun(insertSql, insertParams);
}

function buildCaseUpdateSql(tableName, columnName, idMappings) {
  const cases = [];
  const params = [];
  const whereIds = [];

  for (const [sourceId, targetId] of idMappings.entries()) {
    cases.push("WHEN ? THEN ?");
    params.push(Number(sourceId), Number(targetId));
    whereIds.push(Number(sourceId));
  }

  if (!cases.length) {
    return null;
  }

  const placeholders = whereIds.map(() => "?").join(", ");
  return {
    sql: `
      UPDATE ${tableName}
      SET ${columnName} = CASE ${columnName}
        ${cases.join(" ")}
        ELSE ${columnName}
      END
      WHERE ${columnName} IN (${placeholders})
    `,
    params: [...params, ...whereIds],
  };
}

async function remapSqliteUserReferences(idMappings) {
  if (!idMappings.size) {
    return;
  }

  const referenceTargets = [
    ["solicitudes", "solicitante_id"],
    ["solicitudes", "reviewed_by"],
    ["solicitudes", "dispatched_by"],
    ["solicitudes", "received_by"],
    ["solicitud_historial", "actor_id"],
    ["solicitud_mensajes", "remitente_id"],
    ["solicitud_mensajes", "destinatario_id"],
    ["inventario_movimientos", "actor_id"],
    ["envios_stock", "solicitado_por"],
    ["envios_stock", "autorizado_por"],
    ["notificaciones", "usuario_destino_id"],
    ["usuarios", "archivado_por"],
  ];

  for (const [tableName, columnName] of referenceTargets) {
    const statement = buildCaseUpdateSql(tableName, columnName, idMappings);
    if (!statement) {
      continue;
    }
    await sqliteRun(statement.sql, statement.params);
  }
}

async function replaceSqliteUsers(users) {
  const includeLegacyPassword = await hasLegacyPasswordColumn();
  const existingUsers = await sqliteAll("SELECT id, email FROM usuarios");
  const targetIdByEmail = new Map(users.map((user) => [normalizeEmail(user.email), Number(user.id)]));
  const idMappings = new Map();

  for (const row of existingUsers) {
    const normalizedEmail = normalizeEmail(row.email);
    const targetId = targetIdByEmail.get(normalizedEmail);
    if (!targetId || Number(row.id) === Number(targetId)) {
      continue;
    }
    idMappings.set(Number(row.id), Number(targetId));
  }

  await remapSqliteUserReferences(idMappings);
  await sqliteRun("DELETE FROM usuarios");

  for (const user of users) {
    const insertSql = includeLegacyPassword
      ? `
          INSERT INTO usuarios (
            id,
            nombre,
            email,
            password_hash,
            password,
            rol,
            equipo_id,
            activo,
            archivado,
            fecha_archivado,
            archivado_por,
            fecha_creacion
          )
          VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        `
      : `
          INSERT INTO usuarios (
            id,
            nombre,
            email,
            password_hash,
            rol,
            equipo_id,
            activo,
            archivado,
            fecha_archivado,
            archivado_por,
            fecha_creacion
          )
          VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        `;

    const insertParams = includeLegacyPassword
      ? [
          user.id,
          user.nombre,
          user.email,
          user.password_hash,
          user.password_hash,
          user.rol,
          user.equipo_id,
          user.activo ? 1 : 0,
          user.archivado ? 1 : 0,
          user.fecha_archivado,
          user.archivado_por,
          toSqliteDateTime(user.fecha_creacion) || user.fecha_creacion,
        ]
      : [
          user.id,
          user.nombre,
          user.email,
          user.password_hash,
          user.rol,
          user.equipo_id,
          user.activo ? 1 : 0,
          user.archivado ? 1 : 0,
          user.fecha_archivado,
          user.archivado_por,
          toSqliteDateTime(user.fecha_creacion) || user.fecha_creacion,
        ];

    await sqliteRun(insertSql, insertParams);
  }

  await sqliteRun(
    `
      UPDATE sqlite_sequence
      SET seq = ?
      WHERE name = 'usuarios'
    `,
    [Math.max(...users.map((user) => Number(user.id)), 0)]
  );
}

async function syncMirrorIfNeeded(force = false) {
  if (!PG_ENABLED) {
    return false;
  }

  const now = Date.now();
  if (!force && now - lastMirrorSyncAt < MIRROR_SYNC_TTL_MS) {
    return false;
  }

  const users = await fetchAllPgUsers();

  await sqliteRun("BEGIN IMMEDIATE TRANSACTION");
  try {
    await replaceSqliteUsers(users);
    await sqliteRun("COMMIT");
    lastMirrorSyncAt = now;
    return true;
  } catch (error) {
    await sqliteRun("ROLLBACK");
    throw error;
  }
}

async function initUserStore() {
  if (!PG_ENABLED) {
    return getUserStoreState();
  }

  if (!initPromise) {
    initPromise = (async () => {
      await ensurePgSchema();
      await bootstrapPgUsersFromSqlite();
      await syncMirrorIfNeeded(true);
      return getUserStoreState();
    })();
  }

  return initPromise;
}

function getUserStoreState() {
  return {
    provider: PG_ENABLED ? "postgres" : "sqlite",
    persistent: PG_ENABLED,
    mirror: PG_ENABLED ? "sqlite" : null,
  };
}

async function getSqliteUserById(userId) {
  const equiposMap = await loadEquiposMap();
  const row = await sqliteGet(
    `
      SELECT
        u.id,
        u.nombre,
        u.email,
        u.password_hash,
        u.rol,
        u.equipo_id,
        u.activo,
        COALESCE(u.archivado, 0) AS archivado,
        u.fecha_archivado,
        u.archivado_por,
        u.fecha_creacion,
        e.nombre_equipo AS equipo_nombre
      FROM usuarios u
      LEFT JOIN equipos e ON e.id = u.equipo_id
      WHERE u.id = ?
    `,
    [Number(userId)]
  );
  return mapBaseUser(row, equiposMap);
}

async function getSqliteUserByEmail(email) {
  const equiposMap = await loadEquiposMap();
  const row = await sqliteGet(
    `
      SELECT
        u.id,
        u.nombre,
        u.email,
        u.password_hash,
        u.rol,
        u.equipo_id,
        u.activo,
        COALESCE(u.archivado, 0) AS archivado,
        u.fecha_archivado,
        u.archivado_por,
        u.fecha_creacion,
        e.nombre_equipo AS equipo_nombre
      FROM usuarios u
      LEFT JOIN equipos e ON e.id = u.equipo_id
      WHERE LOWER(TRIM(u.email)) = ?
    `,
    [normalizeEmail(email)]
  );
  return mapBaseUser(row, equiposMap);
}

async function listSqliteUsers(filters = {}) {
  const equiposMap = await loadEquiposMap();
  const estado = String(filters.estado || "activos").trim().toLowerCase();
  const rol = filters.rol ? normalizeRole(filters.rol) : "";
  const search = normalizeText(filters.q || filters.search || "").toLowerCase();
  const params = [];
  const conditions = [];

  if (estado === "activos") {
    conditions.push("u.archivado = 0 AND u.activo = 1");
  } else if (estado === "inactivos") {
    conditions.push("u.archivado = 0 AND u.activo = 0");
  } else if (estado === "archivados") {
    conditions.push("u.archivado = 1");
  }

  if (rol) {
    params.push(rol);
    conditions.push(`u.rol = ?`);
  }

  if (search) {
    const searchValue = `%${search}%`;
    params.push(searchValue, searchValue, searchValue, searchValue);
    conditions.push(`(
      LOWER(COALESCE(u.nombre, '')) LIKE ?
      OR LOWER(COALESCE(u.email, '')) LIKE ?
      OR LOWER(COALESCE(u.rol, '')) LIKE ?
      OR LOWER(COALESCE(e.nombre_equipo, '')) LIKE ?
    )`);
  }

  const rows = await sqliteAll(
    `
      SELECT
        u.id,
        u.nombre,
        u.email,
        u.password_hash,
        u.rol,
        u.equipo_id,
        u.activo,
        COALESCE(u.archivado, 0) AS archivado,
        u.fecha_archivado,
        u.archivado_por,
        u.fecha_creacion,
        e.nombre_equipo AS equipo_nombre
      FROM usuarios u
      LEFT JOIN equipos e ON e.id = u.equipo_id
      ${conditions.length ? `WHERE ${conditions.join(" AND ")}` : ""}
      ORDER BY u.archivado ASC, u.activo DESC, u.id ASC
    `,
    params
  );

  return rows.map((row) => mapBaseUser(row, equiposMap));
}

function buildPgWhere(filters = {}) {
  const estado = String(filters.estado || "activos").trim().toLowerCase();
  const rol = filters.rol ? normalizeRole(filters.rol) : "";
  const conditions = [];
  const params = [];

  if (estado === "activos") {
    conditions.push("archivado = FALSE AND activo = TRUE");
  } else if (estado === "inactivos") {
    conditions.push("archivado = FALSE AND activo = FALSE");
  } else if (estado === "archivados") {
    conditions.push("archivado = TRUE");
  }

  if (rol) {
    params.push(rol);
    conditions.push(`rol = $${params.length}`);
  }

  return {
    where: conditions.length ? `WHERE ${conditions.join(" AND ")}` : "",
    params,
  };
}

async function findUserById(userId) {
  if (!PG_ENABLED) {
    return getSqliteUserById(userId);
  }

  const pg = getPool();
  const { rows } = await pg.query(
    `
      SELECT
        id,
        nombre,
        email,
        password_hash,
        rol,
        equipo_id,
        activo,
        archivado,
        fecha_archivado,
        archivado_por,
        fecha_creacion
      FROM usuarios_auth
      WHERE id = $1
    `,
    [Number(userId)]
  );

  const equiposMap = await loadEquiposMap();
  return mapBaseUser(rows[0], equiposMap);
}

async function findUserByEmail(email) {
  const normalizedEmail = normalizeEmail(email);
  if (!PG_ENABLED) {
    return getSqliteUserByEmail(normalizedEmail);
  }

  const pg = getPool();
  const { rows } = await pg.query(
    `
      SELECT
        id,
        nombre,
        email,
        password_hash,
        rol,
        equipo_id,
        activo,
        archivado,
        fecha_archivado,
        archivado_por,
        fecha_creacion
      FROM usuarios_auth
      WHERE LOWER(BTRIM(email)) = $1
    `,
    [normalizedEmail]
  );

  const equiposMap = await loadEquiposMap();
  return mapBaseUser(rows[0], equiposMap);
}

async function listUsers(filters = {}) {
  if (!PG_ENABLED) {
    return listSqliteUsers(filters);
  }

  const search = normalizeText(filters.q || filters.search || "").toLowerCase();
  const pg = getPool();
  const where = buildPgWhere(filters);
  const { rows } = await pg.query(
    `
      SELECT
        id,
        nombre,
        email,
        password_hash,
        rol,
        equipo_id,
        activo,
        archivado,
        fecha_archivado,
        archivado_por,
        fecha_creacion
      FROM usuarios_auth
      ${where.where}
      ORDER BY archivado ASC, activo DESC, id ASC
    `,
    where.params
  );

  const equiposMap = await loadEquiposMap();
  const mappedUsers = rows.map((row) => mapBaseUser(row, equiposMap));

  if (!search) {
    return mappedUsers;
  }

  return mappedUsers.filter((user) =>
    [user.nombre, user.email, user.rol, user.equipo_nombre]
      .filter(Boolean)
      .some((value) => String(value).toLowerCase().includes(search))
  );
}

async function countOtherActiveAdmins(excludedUserId) {
  if (!PG_ENABLED) {
    const row = await sqliteGet(
      `
        SELECT COUNT(*) AS total
        FROM usuarios
        WHERE rol = ?
          AND activo = 1
          AND COALESCE(archivado, 0) = 0
          AND id <> ?
      `,
      ["ADMIN", Number(excludedUserId)]
    );
    return Number(row?.total || 0);
  }

  const pg = getPool();
  const { rows } = await pg.query(
    `
      SELECT COUNT(*)::int AS total
      FROM usuarios_auth
      WHERE rol = $1
        AND activo = TRUE
        AND archivado = FALSE
        AND id <> $2
    `,
    ["ADMIN", Number(excludedUserId)]
  );

  return Number(rows[0]?.total || 0);
}

async function emailExists(email, excludeUserId = null) {
  const normalizedEmail = normalizeEmail(email);
  if (!PG_ENABLED) {
    const row = excludeUserId
      ? await sqliteGet(
          "SELECT id FROM usuarios WHERE LOWER(TRIM(email)) = ? AND id <> ?",
          [normalizedEmail, Number(excludeUserId)]
        )
      : await sqliteGet("SELECT id FROM usuarios WHERE LOWER(TRIM(email)) = ?", [normalizedEmail]);
    return Boolean(row);
  }

  const pg = getPool();
  const { rows } = excludeUserId
    ? await pg.query(
        "SELECT id FROM usuarios_auth WHERE LOWER(BTRIM(email)) = $1 AND id <> $2 LIMIT 1",
        [normalizedEmail, Number(excludeUserId)]
      )
    : await pg.query("SELECT id FROM usuarios_auth WHERE LOWER(BTRIM(email)) = $1 LIMIT 1", [normalizedEmail]);

  return rows.length > 0;
}

async function createUserRecord(payload) {
  if (!PG_ENABLED) {
    throw new HttpError(500, "createUserRecord requiere PostgreSQL habilitado");
  }

  const pg = getPool();
  const { rows } = await pg.query(
    `
      INSERT INTO usuarios_auth (
        nombre,
        email,
        password_hash,
        rol,
        equipo_id,
        activo,
        archivado,
        fecha_creacion,
        updated_at
      )
      VALUES ($1, $2, $3, $4, $5, $6, FALSE, NOW(), NOW())
      RETURNING
        id,
        nombre,
        email,
        password_hash,
        rol,
        equipo_id,
        activo,
        archivado,
        fecha_archivado,
        archivado_por,
        fecha_creacion
    `,
    [
      normalizeText(payload.nombre),
      normalizeEmail(payload.email),
      payload.password_hash,
      normalizeRole(payload.rol),
      payload.equipo_id ?? null,
      Boolean(payload.activo),
    ]
  );

  const user = mapBaseUser(rows[0], await loadEquiposMap());
  await syncSingleUserToSqlite(user);
  return user;
}

async function updateUserRecord(userId, changes = {}) {
  if (!PG_ENABLED) {
    throw new HttpError(500, "updateUserRecord requiere PostgreSQL habilitado");
  }

  const fields = [];
  const params = [];

  if (Object.prototype.hasOwnProperty.call(changes, "nombre")) {
    params.push(normalizeText(changes.nombre));
    fields.push(`nombre = $${params.length}`);
  }
  if (Object.prototype.hasOwnProperty.call(changes, "email")) {
    params.push(normalizeEmail(changes.email));
    fields.push(`email = $${params.length}`);
  }
  if (Object.prototype.hasOwnProperty.call(changes, "password_hash")) {
    params.push(changes.password_hash);
    fields.push(`password_hash = $${params.length}`);
  }
  if (Object.prototype.hasOwnProperty.call(changes, "rol")) {
    params.push(normalizeRole(changes.rol));
    fields.push(`rol = $${params.length}`);
  }
  if (Object.prototype.hasOwnProperty.call(changes, "equipo_id")) {
    params.push(changes.equipo_id ?? null);
    fields.push(`equipo_id = $${params.length}`);
  }
  if (Object.prototype.hasOwnProperty.call(changes, "activo")) {
    params.push(Boolean(changes.activo));
    fields.push(`activo = $${params.length}`);
  }
  if (Object.prototype.hasOwnProperty.call(changes, "archivado")) {
    params.push(Boolean(changes.archivado));
    fields.push(`archivado = $${params.length}`);
  }
  if (Object.prototype.hasOwnProperty.call(changes, "fecha_archivado")) {
    params.push(changes.fecha_archivado || null);
    fields.push(`fecha_archivado = $${params.length}`);
  }
  if (Object.prototype.hasOwnProperty.call(changes, "archivado_por")) {
    params.push(changes.archivado_por ?? null);
    fields.push(`archivado_por = $${params.length}`);
  }

  if (!fields.length) {
    return findUserById(userId);
  }

  params.push(Number(userId));
  const pg = getPool();
  const { rows } = await pg.query(
    `
      UPDATE usuarios_auth
      SET ${fields.join(", ")}, updated_at = NOW()
      WHERE id = $${params.length}
      RETURNING
        id,
        nombre,
        email,
        password_hash,
        rol,
        equipo_id,
        activo,
        archivado,
        fecha_archivado,
        archivado_por,
        fecha_creacion
    `,
    params
  );

  if (!rows.length) {
    throw new HttpError(404, "Usuario no encontrado");
  }

  const user = mapBaseUser(rows[0], await loadEquiposMap());
  await syncSingleUserToSqlite(user);
  return user;
}

module.exports = {
  initUserStore,
  getUserStoreState,
  getPgPool: getPool,
  syncMirrorIfNeeded,
  findUserById,
  findUserByEmail,
  listUsers,
  countOtherActiveAdmins,
  emailExists,
  createUserRecord,
  updateUserRecord,
};
